In [4]:
#import library terlebih dahulu
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
#panggil data asurabsi_mobil di excel
#pastikan sudah di folder yang sama
asuransi_mobil = pd.read_csv('asuransi_mobil.csv')
print(asuransi_mobil)

      Unnamed: 0  IDENTITAS                  UMUR JENIS_KELAMIN  \
0              0     569520   lebih dari 65 tahun     perempuan   
1              1     750365  kurang dari 25 tahun     laki-laki   
2              2     199901  kurang dari 25 tahun     perempuan   
3              3     478866  kurang dari 25 tahun     laki-laki   
4              4     731664    antara 25-40 tahun     laki-laki   
...          ...        ...                   ...           ...   
9995        9995     323164    antara 25-40 tahun     perempuan   
9996        9996     910346    antara 25-40 tahun     perempuan   
9997        9997     468409    antara 25-40 tahun     laki-laki   
9998        9998     903459    antara 25-40 tahun     perempuan   
9999        9999     442696    antara 25-40 tahun     perempuan   

      PENGALAMAN_MENGEMUDI   PENDIDIKAN        PENGHASILAN  SKOR_KREDIT  \
0     kurang dari 10 tahun          SMA  lebih dari 3x UMR     0.629027   
1     kurang dari 10 tahun    tidak ada    ku

In [7]:
asuransi_mobil.head()

Unnamed: 0  IDENTITAS                  UMUR JENIS_KELAMIN  \
0           0     569520   lebih dari 65 tahun     perempuan   
1           1     750365  kurang dari 25 tahun     laki-laki   
2           2     199901  kurang dari 25 tahun     perempuan   
3           3     478866  kurang dari 25 tahun     laki-laki   
4           4     731664    antara 25-40 tahun     laki-laki   

   PENGALAMAN_MENGEMUDI   PENDIDIKAN        PENGHASILAN  SKOR_KREDIT  \
0  kurang dari 10 tahun          SMA  lebih dari 3x UMR     0.629027   
1  kurang dari 10 tahun    tidak ada    kurang dari UMR     0.357757   
2  kurang dari 10 tahun          SMA    antara 1-2x UMR     0.493146   
3  kurang dari 10 tahun  universitas    antara 1-2x UMR     0.206013   
4    antara 10-20 tahun    tidak ada    antara 1-2x UMR     0.388366   

  PEMILIK_KENDARAAN TAHUN_PRODUKSI         STATUS       ANAK  KODE_POS  \
0                ya   setelah 2020  belum menikah        ada     10238   
1             tidak   sebelum 2020  belum menikah  tidak ada     10238   
2                ya   sebelum 2020  belum menikah  tidak ada     10238   
3                ya   sebelum 2020  belum menikah        ada     32765   
4                ya   sebelum 2020  belum menikah  tidak ada     32765   

   KM_PER_TAHUN JENIS_KENDARAAN  TILANG_NGEBUT  TILANG_MABUK  \
0       12000.0        keluarga              0             0   
1       16000.0        keluarga              0             0   
2       11000.0        keluarga              0             0   
3       11000.0        keluarga              0             0   
4       12000.0        keluarga              2             0   

   KECELAKAAN_SEBELUMNYA  KLAIM  
0                      0  tidak  
1                      0     ya  
2                      0  tidak  
3                      0  tidak  
4                      1     ya

In [9]:
asuransi_mobil.describe()

Unnamed: 0      IDENTITAS  SKOR_KREDIT      KODE_POS  KM_PER_TAHUN  \
count  10000.00000   10000.000000  9018.000000  10000.000000   9043.000000   
mean    4999.50000  500521.906800     0.515813  19864.548400  11697.003207   
std     2886.89568  290030.768758     0.137688  18915.613855   2818.434528   
min        0.00000     101.000000     0.053358  10238.000000   2000.000000   
25%     2499.75000  249638.500000     0.417191  10238.000000  10000.000000   
50%     4999.50000  501777.000000     0.525033  10238.000000  12000.000000   
75%     7499.25000  753974.500000     0.618312  32765.000000  14000.000000   
max     9999.00000  999976.000000     0.960819  92101.000000  22000.000000   

       TILANG_NGEBUT  TILANG_MABUK  KECELAKAAN_SEBELUMNYA  
count   10000.000000   10000.00000           10000.000000  
mean        1.482900       0.23920               1.056300  
std         2.241966       0.55499               1.652454  
min         0.000000       0.00000               0.000000  
25%         0.000000       0.00000               0.000000  
50%         0.000000       0.00000               0.000000  
75%         2.000000       0.00000               2.000000  
max        22.000000       6.00000              15.000000

In [10]:
# Melihat type data apakah berupa integer, bilangan desimal, atau data kategori
asuransi_mobil.dtypes

Unnamed: 0                 int64
IDENTITAS                  int64
UMUR                      object
JENIS_KELAMIN             object
PENGALAMAN_MENGEMUDI      object
PENDIDIKAN                object
PENGHASILAN               object
SKOR_KREDIT              float64
PEMILIK_KENDARAAN         object
TAHUN_PRODUKSI            object
STATUS                    object
ANAK                      object
KODE_POS                   int64
KM_PER_TAHUN             float64
JENIS_KENDARAAN           object
TILANG_NGEBUT              int64
TILANG_MABUK               int64
KECELAKAAN_SEBELUMNYA      int64
KLAIM                     object
dtype: object

In [11]:
# mengecek apakah terdapat data yang kosong
asuransi_mobil.isnull().sum()

Unnamed: 0                 0
IDENTITAS                  0
UMUR                       0
JENIS_KELAMIN              0
PENGALAMAN_MENGEMUDI       0
PENDIDIKAN                 0
PENGHASILAN                0
SKOR_KREDIT              982
PEMILIK_KENDARAAN          0
TAHUN_PRODUKSI             0
STATUS                     0
ANAK                       0
KODE_POS                   0
KM_PER_TAHUN             957
JENIS_KENDARAAN            0
TILANG_NGEBUT              0
TILANG_MABUK               0
KECELAKAAN_SEBELUMNYA      0
KLAIM                      0
dtype: int64

In [34]:
# Drop data bentuk numeric karena akan dinormalisasi dulu
asuransi_mobil.drop(columns=["SKOR_KREDIT", "KM_PER_TAHUN"])

Unnamed: 0  IDENTITAS  UMUR JENIS_KELAMIN  PENGALAMAN_MENGEMUDI  \
0              0     569520     1     perempuan  kurang dari 10 tahun   
1              1     750365     4     laki-laki  kurang dari 10 tahun   
2              2     199901     4     perempuan  kurang dari 10 tahun   
3              3     478866     4     laki-laki  kurang dari 10 tahun   
4              4     731664     3     laki-laki    antara 10-20 tahun   
...          ...        ...   ...           ...                   ...   
9995        9995     323164     3     perempuan    antara 10-20 tahun   
9996        9996     910346     3     perempuan    antara 10-20 tahun   
9997        9997     468409     3     laki-laki  kurang dari 10 tahun   
9998        9998     903459     3     perempuan    antara 10-20 tahun   
9999        9999     442696     3     perempuan  kurang dari 10 tahun   

       PENDIDIKAN        PENGHASILAN PEMILIK_KENDARAAN TAHUN_PRODUKSI  \
0             SMA  lebih dari 3x UMR                ya   setelah 2020   
1       tidak ada    kurang dari UMR             tidak   sebelum 2020   
2             SMA    antara 1-2x UMR                ya   sebelum 2020   
3     universitas    antara 1-2x UMR                ya   sebelum 2020   
4       tidak ada    antara 1-2x UMR                ya   sebelum 2020   
...           ...                ...               ...            ...   
9995  universitas  lebih dari 3x UMR                ya   sebelum 2020   
9996    tidak ada    antara 2-3x UMR                ya   setelah 2020   
9997          SMA    antara 2-3x UMR                ya   sebelum 2020   
9998          SMA    kurang dari UMR             tidak   sebelum 2020   
9999    tidak ada    antara 1-2x UMR                ya   sebelum 2020   

             STATUS       ANAK  KODE_POS JENIS_KENDARAAN  TILANG_NGEBUT  \
0     belum menikah        ada     10238        keluarga              0   
1     belum menikah  tidak ada     10238        keluarga              0   
2     belum menikah  tidak ada     10238        keluarga              0   
3     belum menikah        ada     32765        keluarga              0   
4     belum menikah  tidak ada     32765        keluarga              2   
...             ...        ...       ...             ...            ...   
9995  belum menikah  tidak ada     10238        keluarga              0   
9996  belum menikah        ada     32765        keluarga              1   
9997  belum menikah        ada     10238        keluarga              0   
9998  belum menikah        ada     10238        keluarga              2   
9999        menikah        ada     10238        keluarga              0   

      TILANG_MABUK  KECELAKAAN_SEBELUMNYA  KLAIM  
0                0                      0  tidak  
1                0                      0     ya  
2                0                      0  tidak  
3                0                      0  tidak  
4                0                      1     ya  
...            ...                    ...    ...  
9995             0                      1  tidak  
9996             0                      0  tidak  
9997             0                      0  tidak  
9998             0                      1     ya  
9999             0                      0  tidak  

[10000 rows x 17 columns]

In [30]:
# Melihat apa saja isi dari kolom IDENTITAS
asuransi_mobil.IDENTITAS.unique()

array([569520, 750365, 199901, ..., 468409, 903459, 442696], dtype=int64)

In [13]:
# Melihat apa saja isi dari kolom UMUR

array(['lebih dari 65 tahun', 'kurang dari 25 tahun',
       'antara 25-40 tahun', 'antara 40-65 tahun'], dtype=object)

In [14]:
# Melihat apa saja isi dari kolom JENIS_KELAMIN
asuransi_mobil.JENIS_KELAMIN.unique()

array(['perempuan', 'laki-laki'], dtype=object)

In [15]:
# Melihat apa saja isi dari kolom PENGALAMAN_MENGEMUDI
asuransi_mobil.PENGALAMAN_MENGEMUDI.unique()

array(['kurang dari 10 tahun', 'antara 10-20 tahun', 'antara 20-30 tahun',
       'lebih dari 30 tahun'], dtype=object)

In [16]:
# Melihat apa saja isi dari kolom PENDIDIKAN 
asuransi_mobil.PENDIDIKAN.unique()

array(['SMA', 'tidak ada', 'universitas'], dtype=object)

In [17]:
# Melihat apa saja isi dari kolom PENGHASILAN 
asuransi_mobil.PENGHASILAN.unique()

array(['lebih dari 3x UMR', 'kurang dari UMR', 'antara 1-2x UMR',
       'antara 2-3x UMR'], dtype=object)

In [18]:
# Melihat apa saja isi dari kolom SKOR_KREDIT 
asuransi_mobil.SKOR_KREDIT.unique()

array([0.62902731, 0.35775712, 0.49314579, ..., 0.47094023, 0.36418478,
       0.43522478])

In [19]:
# Melihat apa saja isi dari kolom PEMILIK_KENDARAAN 
asuransi_mobil.PEMILIK_KENDARAAN.unique()

array(['ya', 'tidak'], dtype=object)

In [20]:
# Melihat apa saja isi dari kolom TAHUN_PRODUKSI 
asuransi_mobil.TAHUN_PRODUKSI.unique()

array(['setelah 2020', 'sebelum 2020'], dtype=object)

In [21]:
# Melihat apa saja isi dari kolom STATUS 
asuransi_mobil.STATUS.unique()

array(['belum menikah', 'menikah'], dtype=object)

In [22]:
# Melihat apa saja isi dari kolom ANAK 
asuransi_mobil.ANAK.unique()

array(['ada', 'tidak ada'], dtype=object)

In [23]:
# Melihat apa saja isi dari kolom KODE_POS 
asuransi_mobil.KODE_POS.unique()

array([10238, 32765, 92101, 21217], dtype=int64)

In [24]:
# Melihat apa saja isi dari kolom KM_PER_TAHUN 
asuransi_mobil.KM_PER_TAHUN.unique()

array([12000., 16000., 11000., 13000., 14000., 10000.,  8000.,    nan,
       18000., 17000.,  7000., 15000.,  9000.,  5000.,  6000., 19000.,
        4000.,  3000.,  2000., 20000., 21000., 22000.])

In [37]:
# Melihat apa saja isi dari kolom JENIS_KENDARAAN 
asuransi_mobil.JENIS_KENDARAAN.unique()

array(['keluarga', 'sport'], dtype=object)

In [26]:
# Melihat apa saja isi dari kolom TILANG_NGEBUT 
asuransi_mobil.TILANG_NGEBUT.unique()

array([ 0,  2,  3,  7,  6,  4, 10, 13,  1,  5,  9,  8, 12, 11, 15, 17, 19,
       18, 16, 14, 22], dtype=int64)

In [27]:
# Melihat apa saja isi dari kolom TILANG_MABUK 
asuransi_mobil.TILANG_MABUK.unique()

array([0, 2, 1, 3, 4, 5, 6], dtype=int64)

In [28]:
# Melihat apa saja isi dari kolom KECELAKAAN_SEBELUMNYA 
asuransi_mobil.KECELAKAAN_SEBELUMNYA.unique()

array([ 0,  1,  3,  7,  2,  5,  4,  6,  8, 10, 11,  9, 12, 14, 15],
      dtype=int64)

In [29]:
# Melihat apa saja isi dari kolom KLAIM 
asuransi_mobil.KLAIM.unique()

array(['tidak', 'ya'], dtype=object)

In [32]:
# Melakukan mapping dari UMUR karena walaupun UMUR merupakan data kategori, akan tetapi terdapat peningkatan
asuransi_mobil['UMUR'] = \
asuransi_mobil['UMUR'].map({'lebih dari 65 tahun':1,'antara 40-65 tahun':2,'antara 25-40 tahun':3,'kurang dari 25 tahun':4})

In [35]:
# Melakukan mapping dari PENGALAMAN_MENGEMUDI karena walaupun PENGALAMAN_MENGEMUDI merupakan data kategori, akan tetapi terdapat peningkatan
asuransi_mobil['PENGALAMAN_MENGEMUDI'] = \
asuransi_mobil['PENGALAMAN_MENGEMUDI'].map({'lebih dari 30 tahun':1,'antara 20-30 tahun':2,'antara 10-20 tahun':3,'kurang dari 10 tahun':4})

In [36]:
# Melakukan maping dari PENGHASILAN
asuransi_mobil['PENGHASILAN'] = \
asuransi_mobil['PENGHASILAN'].map({'lebih dari 3x UMR':1,'antara 2-3x UMR':2,'antara 1-2x UMR':3,'kurang dari UMR':4})

In [ ]:
# Melakukan maping dari TAHUN_PRODUKSI
asuransi_mobil['TAHUN_PRODUKSI'] = \
asuransi_mobil['TAHUN_PRODUKSI'].map({'setelah 2020':1,'sebelum 2020':2})

In [ ]:
# Melakukan maping dari JENIS_KENDARAAN
asuransi_mobil['JENIS_KENDARAAN'] = \
asuransi_mobil['JENIS_KENDARAAN'].map({'sport':1,'keluarga':2})

In [45]:
data_categorical = ['JENIS_KELAMIN', ' PEMILIK_KENDARAAN', 'STATUS', 'ANAK', 'JENIS_KENDARAAN']
data_numeric = ['UMUR', 'PENGALAMAN_MENGEMUDI', 'PENGHASILAN']
data_binary = ['TAHUN_PRODUKSI']
data_target = ['KLAIM']

In [47]:
# Normalisasi data dalam bentuk numerik
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()
d = scaler.fit_transform(asuransi_mobil[data_numeric])
data_normalisasi = pd.DataFrame(d, columns=asuransi_mobil[data_numeric].columns)
data_normalisasi.head(10)

UMUR  PENGALAMAN_MENGEMUDI  PENGHASILAN
0  0.000000              1.000000     0.000000
1  1.000000              1.000000     1.000000
2  1.000000              1.000000     0.666667
3  1.000000              1.000000     0.666667
4  0.666667              0.666667     0.666667
5  0.333333              0.333333     0.000000
6  0.000000              0.000000     0.000000
7  0.666667              1.000000     0.666667
8  0.333333              0.333333     0.666667
9  0.333333              1.000000     0.000000

In [53]:
X = asuransi_mobil.drop(['KLAIM'], axis =1) 
y = asuransi_mobil['KLAIM']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [56]:
from sklearn.svm import SVC
model_svm = SVC()

In [59]:
model_svm.fit(X_train,y_train)

ValueError: could not convert string to float: 'perempuan'